spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codenemsy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1004

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: kr.or.kosa.backend.freeboard.dto
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8090